
variables:
  PACKAGE: template
  WHEEL_NAME: template
  JOB_WITH_COVERAGE: test_functional
  GITLAB_URL: https://scm.atosresearch.eu
  SNS_REGISTRY_COMMON: registry.atosresearch.eu:18467
  #SONAR_Project: tmt-smartnet-template

stages:
  - build
  - unit_functional_tests
  - release

build_wheel:
  image: $SNS_REGISTRY_COMMON/python:3.8-slim
  stage: build
  only:
    - master
    - develop
    - merge_requests
  before_script: # Cannot be added due to CI_JOB_TOKEN policy?
    # Used to install sns.logger from git+https instead of --extra-index-url ${NEXUS_PYPI_URL_DOWNLOAD}
    - echo "USER_PASSWORD=${CI_JOB_TOKEN}" >> .env
    - echo "USER_NAME=gitlab-ci-token" >> .env
    - echo "This has been executed"
  script: # TODO: learn how to share venv
    - pip install -e .

test_functional:
  image: $SNS_REGISTRY_COMMON/python:3.8-slim
  stage: unit_functional_tests
  dependencies:
    - build_wheel
  only:
    - master
    - develop
    - merge_requests

  before_script: # Cannot be added to parent due to CI_JOB_TOKEN policy?
  
    # Used to install sns.logger from git+https instead of --extra-index-url ${NEXUS_PYPI_URL_DOWNLOAD}
    - echo "USER_PASSWORD=${CI_JOB_TOKEN}" >> .env
    - echo "USER_NAME=gitlab-ci-token" >> .env
    - echo "This has been executed"
  script:
    - echo "Installing ${PACKAGE} in develop mode for coverage purpose"
    
    - cat .env
	
    - pip install -e .  # tests need to run in develop-mode installed to be able to read coverage
    - pytest tests --cov=${PACKAGE} --cov-report html --cov-report term-missing
    - cp -r htmlcov reports
  coverage: '/TOTAL.+?(\d+%)/'

  artifacts:
    paths:
      - reports/htmlcov

test_pylint:
  image: $SNS_REGISTRY_COMMON/cython:3.8-cicd
  stage: unit_functional_tests
  dependencies:
    - build_wheel
  only:
    - master
    - develop
    - merge_requests
  before_script: # Cannot be added to parent due to CI_JOB_TOKEN policy?
    # Used to install sns.logger from git+https instead of --extra-index-url ${NEXUS_PYPI_URL_DOWNLOAD}
    - echo "USER_PASSWORD=${CI_JOB_TOKEN}" >> .env
    - echo "USER_NAME=gitlab-ci-token" >> .env
    - echo "This has been executed"
  script:
    - pip install -e .
    # pylint will fail return non-zero even if only warnings are found
    - pylint $PACKAGE tests --exit-zero --reports y >> qa_report.txt
    - cat qa_report.txt
    - pylint_wrapper --pylint-report-path qa_report.txt raise-for-code
    - mkdir reports/
    - cp qa_report.txt reports/
  artifacts:
    paths:
      - reports/qa_report.txt

make_badges: # Only update when merged to main branches
  image: $SNS_REGISTRY_COMMON/cython:3.8-cicd
  stage: release
  dependencies:
    - test_pylint
    - build_wheel
  only:
    - master
    - develop
    - merge_requests
  before_script: # Cannot be added to parent due to CI_JOB_TOKEN policy?
    # Used to install sns.logger from git+https instead of --extra-index-url ${NEXUS_PYPI_URL_DOWNLOAD}
    - echo "USER_PASSWORD=${CI_JOB_TOKEN}" >> .env
    - echo "USER_NAME=gitlab-ci-token" >> .env
    - echo "This has been executed"
  script:
    - apt-get update
    - pip install -e .
    - QA=$(pylint_wrapper --pylint-report-path reports/qa_report.txt get-qa-value | tail -1)
    - echo ${QA}
    - VERSION=$(python -c "import pkg_resources; print(pkg_resources.get_distribution('$WHEEL_NAME').version)")  # TODO: parse from dist/
    - echo ${VERSION}
    - gitlab_wrapper create-badge-file --url $GITLAB_URL --api-token ${API_TOKEN}
      --project-id ${CI_PROJECT_ID} --pipeline-id ${CI_PIPELINE_ID} --badge-key Coverage --file-name Coverage.svg --badge-colour COVERAGE
      --test-job-name $JOB_WITH_COVERAGE
    - gitlab_wrapper create-badge-file --badge-key Pylint --badge-value ${QA} --file-name Pylint.svg --badge-colour QA
    - gitlab_wrapper create-badge-file --badge-key Version --badge-value ${VERSION} --file-name Version.svg --badge-colour VERSION
  artifacts:
    paths:
      - Coverage.svg
      - Version.svg
      - Pylint.svg

